### PR TITLE
Fix #91: wrong comment date after rotation

### LINKED ISSUE #89: Links target URL get truncated in comments
Hi,

When users include links in their comment, they sometimes point to the truncated URL that appears in the text instead of the actual and full URL. It doesn't happen directly after loading the comments but only after browsing them a bit.

I was unable to find a clear pattern, but here is a scenario:
1. Load in Pumpkin Reader [this recent news](https://news.ycombinator.com/item?id=10481507) which contains some visually truncated links
2. Scroll down as you do when browsing comments
3. Click on a visually truncated comment
4. The browser tries to open the truncated URL instead of the actual URL

You can even see a visual difference when it happens:
- After loading the comments, the first comment's link looks like [this](https://drive.google.com/open?id=0B-gWAI-JybKRUVAyOWFmWkJCOGs).
- After browsing the comments and coming back to the first comment, it looks like [this](https://drive.google.com/open?id=0B-gWAI-JybKRV2pGQVBWVFg5LUk).

Thanks for this excellent HN client!

### LINKED ISSUE #91: Wrong comment dates after screen rotation
When on the comment section, rotating the screen causes all dates to have bad values.
- [Before rotation](https://drive.google.com/open?id=0B-gWAI-JybKRUnhuc0pzME9GUGc)
- [After rotation](https://drive.google.com/open?id=0B-gWAI-JybKRbXY0a2JoaFFubm8)

### PR DESCRIPTION
**Pull request by timotiusnc**
Fixes #91.

It's seconds/milliseconds error.

From HN API: seconds.
Java Date object needs: milliseconds.

When rotation change: we call onSaveStateChange and save the comments into Parcelable objects, then we reconstruct it using `Item#getTime().getTime()` which returns milliseconds. Then we multiply it again with 1000 on `Item`'s constructor, then again with 1000 on `Item`'s `getTime()`.

### CODE REVIEW

File: app/src/main/java/io/pumpkinz/pumpkinreader/model/Item.java [hunk 1]
```diff
@@ -1,5 +1,7 @@
 package io.pumpkinz.pumpkinreader.model;
 
+import android.util.Log;
```
Comment (wiseodd) [inline app/src/main/java/io/pumpkinz/pumpkinreader/model/Item.java]: Useful tip: make code formatter also optimize imports.
So this one right here will be removed automatically when you format the code

**Comment by timotiusnc** [comment]
Updated!
